spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: candidate-service
          uri: lb://CANDIDATE-SERVICE
          predicates:
            - Path=/candidate/**
        - id: recruit-service
            uri: lb://RECRUIT-SERVICE
            predicates:
              - Path=/recruit/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8989